import '../_assets/css/globals.css';

import clsx from 'clsx';
import type { Metadata } from 'next';

import { fontGeistMono, fontGeistSans } from '../(shared)/_theme';

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: { icon: '/favicon.ico' },
  };
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={clsx([fontGeistSans.variable, fontGeistMono.variable, 'h-full antialiased'])}
    >
      <body>{children}</body>
    </html>
  );
}
